Repository codestates-seb/seb41_main_036, pull requests merged in 2023-01, with the labels that each got.

#10 design: globalcss추가
  project/src/index.css
Labels: FrontEnd

#20 Feature: 명소 페이지 생성
  project/node_modules/.cache/default-development/0.pack
  project/node_modules/.cache/default-development/index.pack
  project/package-lock.json
  project/package.json
  project/src/App.css
  project/src/Main.tsx
  project/src/dummyData.json
  project/src/index.css
  project/src/pages/Place.tsx
Labels: 정세민, FrontEnd, Bare

#55 feat: header 컴포넌트 완성
  project/src/Main.tsx
  project/src/components/Header/FixedOnScrollUpHeader.tsx
  project/src/components/Header/HiddenHeader.tsx
  project/src/components/Header/SearchBar.tsx
  project/src/components/Header/SuggestionBox.tsx
  project/src/components/Header/index.tsx
  project/src/components/Header/style.tsx
  project/src/data/searchBarData.tsx
  project/src/index.css
  project/src/utils/functions.tsx
  project/src/utils/useClickScrollDetect.tsx
Labels: 김진주, FrontEnd, Bare

#85 feat: carousel 컴포넌트 구현 #56 - useusername1
  project/package-lock.json
  project/package.json
  project/src/Main.tsx
  project/src/components/Carousel/CarouselContent.tsx
  project/src/components/Carousel/index.tsx
  project/src/components/Carousel/style.tsx
  project/src/components/GoogleLogin.js
  project/src/data/CarouselData.ts
  project/src/data/searchBarData.ts
Labels: 김진주, FrontEnd, Bare

#89 feat: ranking 컴포넌트 구현(#86)-useusername1
  project/src/Main.tsx
  project/src/components/Ranking/index.tsx
  project/src/components/Ranking/style.tsx
  project/src/data/RankingData.ts
Labels: 김진주, FrontEnd, Bare

#128 Feature: 포스트 수정 페이지 기능 구현
  project/src/pages/DetailPost.tsx
  project/src/pages/EditPost .tsx
  project/src/pages/WritePost.tsx
Labels: 정세민, FrontEnd, Bare

#133 Feature: Footer 구현
  project/public/logo-git.png
  project/public/logo2.jpg
  project/src/components/Footer.tsx
  project/src/components/FooterStyled.ts
  project/src/pages/DetailPost.tsx
  project/src/pages/Main.tsx
  project/src/pages/Place.tsx
  project/src/pages/PlaceDetail.tsx
  project/src/pages/Post.tsx
Labels: 정세민, FrontEnd, Bare

#136 fix: 포스트 작성페이지 명소Id 라우터 추가
  project/src/App.tsx
  project/src/pages/PlaceDetail.tsx
  project/src/pages/WritePost.tsx
Labels: 정세민, FrontEnd, Bare

#141 Feature: MyPage 페이지네이션 생성 및 구현
  project/src/components/MyPagePagination.tsx
  project/src/pages/MyPage.tsx
Labels: 정세민, FrontEnd, Bare
